service:
  internalPort: 3000
  externalPort: 3000

ingress:
  annotations:
    kubernetes.io/ingress.class: istio
    kubernetes.io/tls-acme: "true"

replicaCount: 2
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  # See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # for examples of each.
  targetCPUUtilizationPercentage: 80
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

resources:
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 3
  path: /

readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 3
  path: /

serviceAccount:
  create: false  # 기존 서비스 어카운트를 사용하는 경우 true 대신 false를 사용합니다.
  name:  # 사용하고자 하는 서비스 어카운트의 이름을 지정합니다. ( 서비스 어카운트 생성 : devops engineer 업무 - https://www.notion.so/memecore/dev-eks-IRSA-c325c11cfbdb41439ae5783ee8005136?pvs=4 )

extraEnv:
  - name: APP_ENV
    value: production
  - name: SECRET_NAME
    value:  # 해당 프로젝트에서 사용할 aws secrets manager 의 secret name 값 ( 프로젝트별 달라지는 값을 하드 코딩하지 않고 entrypoint.sh 에서 사용됨 )

# 클러스터 구성을 관리형 노드그룹(manage-group)과 서비스 노드그룹(service-group) 을 분리하였으므로, 해당 tag를 통해 서비스용 노드그룹에 배치 될 수 있게 합니다.
nodeSelector:
  alpha.eksctl.io/nodegroup-name: service-group
